### ISSUE TITLE
When collapsing a thread browser should return to top of the next thread

### ISSUE THREAD

**Issue by cheezecat** [maksverver/astral-codex-eleven#3]
Currently when you collapse a thread that you are half way through your screen position stays the same and the following threads get pulled up, leaving you looking at the middle of some later thread.  Would be great if thread collapsing moved you to the beginning of the next thread.

(Otherwise awesome, makes ACX comments bearable.)

**Comment by maksverver** [comment]
Great idea; thanks for suggesting it!

I implemented this slightly differently: by keeping the collapsed comment itself into view. This has the advantage that it's clear which comment was just collapsed, and makes it easy to expand it again without having to scroll up, in case it was collapsed by mistake. It still has the desired effect of not scrolling past comments below the collapsed comment thread.
